org.gradle.jvmargs=-Xmx2048m -Xms512m -XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx768m -XX:MaxMetaspaceSize=256m

org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
android.useAndroidX=true
android.enableJetifier=true